{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "516e7924-2980-40f6-8304-013d82c39a16",
   "metadata": {},
   "source": [
    "### Q1. Explain why we have to use the Exception class while creating a Custom Exception. Note: Here Exception class refers to the base class for all the exceptions.\n",
    "\n",
    "#### Answer:"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6daedd16-47cf-40d7-9aee-059457cee0c0",
   "metadata": {},
   "source": [
    "When creating a custom exception in Python, it is recommended to inherit from the built-in Exception class or one of its subclasses. The Exception class serves as the base class for all exceptions in Python. By deriving from the Exception class, you ensure that your custom exception inherits the basic behavior and attributes of an exception, such as the ability to be raised, caught, and processed by exception handlers.\n",
    "\n",
    "Inheriting from the Exception class also allows your custom exception to be caught by more general exception handlers that are designed to handle a broader range of exceptions. For example, if you have a try-except block that catches exceptions of type Exception, it will also catch your custom exception since it is a subclass of Exception.\n",
    "\n",
    "Additionally, the Exception class provides useful methods and attributes that can be utilized in exception handling. These include __str__ (to provide a string representation of the exception), args (to access any arguments passed to the exception), and with_traceback (to associate a traceback with the exception)."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eb4389f5-eac5-4661-9a7d-b50284cb70f3",
   "metadata": {},
   "source": [
    "### Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "#### Answer:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9cf1fe5c-ac9c-4fda-a8ce-f618cc28b372",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b7e238a7-8d85-4320-b39b-172feeb242e8",
   "metadata": {},
   "outputs": [],
   "source": [
    "def print_exception_hierarchy(exception_class, level=0):\n",
    "    indent = ' ' * level\n",
    "    print(indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, level + 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "cdf154a4-d13a-4071-a723-c6642d435305",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      " Exception\n",
      "  TypeError\n",
      "   FloatOperation\n",
      "   MultipartConversionError\n",
      "  StopAsyncIteration\n",
      "  StopIteration\n",
      "  ImportError\n",
      "   ModuleNotFoundError\n",
      "   ZipImportError\n",
      "  OSError\n",
      "   ConnectionError\n",
      "    BrokenPipeError\n",
      "    ConnectionAbortedError\n",
      "    ConnectionRefusedError\n",
      "    ConnectionResetError\n",
      "     RemoteDisconnected\n",
      "   BlockingIOError\n",
      "   ChildProcessError\n",
      "   FileExistsError\n",
      "   FileNotFoundError\n",
      "   IsADirectoryError\n",
      "   NotADirectoryError\n",
      "   InterruptedError\n",
      "    InterruptedSystemCall\n",
      "   PermissionError\n",
      "   ProcessLookupError\n",
      "   TimeoutError\n",
      "   UnsupportedOperation\n",
      "   itimer_error\n",
      "   herror\n",
      "   gaierror\n",
      "   SSLError\n",
      "    SSLCertVerificationError\n",
      "    SSLZeroReturnError\n",
      "    SSLWantWriteError\n",
      "    SSLWantReadError\n",
      "    SSLSyscallError\n",
      "    SSLEOFError\n",
      "   Error\n",
      "    SameFileError\n",
      "   SpecialFileError\n",
      "   ExecError\n",
      "   ReadError\n",
      "   URLError\n",
      "    HTTPError\n",
      "    ContentTooShortError\n",
      "   BadGzipFile\n",
      "  EOFError\n",
      "   IncompleteReadError\n",
      "  RuntimeError\n",
      "   RecursionError\n",
      "   NotImplementedError\n",
      "    ZMQVersionError\n",
      "    StdinNotImplementedError\n",
      "   _DeadlockError\n",
      "   BrokenBarrierError\n",
      "   BrokenExecutor\n",
      "    BrokenThreadPool\n",
      "   SendfileNotAvailableError\n",
      "   ExtractionError\n",
      "   VariableError\n",
      "  NameError\n",
      "   UnboundLocalError\n",
      "  AttributeError\n",
      "   FrozenInstanceError\n",
      "  SyntaxError\n",
      "   IndentationError\n",
      "    TabError\n",
      "  LookupError\n",
      "   IndexError\n",
      "   KeyError\n",
      "    NoSuchKernel\n",
      "    UnknownBackend\n",
      "   CodecRegistryError\n",
      "  ValueError\n",
      "   UnicodeError\n",
      "    UnicodeEncodeError\n",
      "    UnicodeDecodeError\n",
      "    UnicodeTranslateError\n",
      "   UnsupportedOperation\n",
      "   JSONDecodeError\n",
      "   SSLCertVerificationError\n",
      "   Error\n",
      "   UnsupportedDigestmodError\n",
      "   IllegalMonthError\n",
      "   IllegalWeekdayError\n",
      "   ParserError\n",
      "   ClassNotFound\n",
      "   ClipboardEmpty\n",
      "   MessageDefect\n",
      "    NoBoundaryInMultipartDefect\n",
      "    StartBoundaryNotFoundDefect\n",
      "    CloseBoundaryNotFoundDefect\n",
      "    FirstHeaderLineIsContinuationDefect\n",
      "    MisplacedEnvelopeHeaderDefect\n",
      "    MissingHeaderBodySeparatorDefect\n",
      "    MultipartInvariantViolationDefect\n",
      "    InvalidMultipartContentTransferEncodingDefect\n",
      "    UndecodableBytesDefect\n",
      "    InvalidBase64PaddingDefect\n",
      "    InvalidBase64CharactersDefect\n",
      "    InvalidBase64LengthDefect\n",
      "    HeaderDefect\n",
      "     InvalidHeaderDefect\n",
      "     HeaderMissingRequiredValue\n",
      "     NonPrintableDefect\n",
      "     ObsoleteHeaderDefect\n",
      "     NonASCIILocalPartDefect\n",
      "     InvalidDateDefect\n",
      "   MacroToEdit\n",
      "   InvalidFileException\n",
      "   UnequalIterablesError\n",
      "   InvalidVersion\n",
      "   _InvalidELFFileHeader\n",
      "   InvalidWheelFilename\n",
      "   InvalidSdistFilename\n",
      "   InvalidSpecifier\n",
      "   InvalidMarker\n",
      "   UndefinedComparison\n",
      "   UndefinedEnvironmentName\n",
      "   InvalidRequirement\n",
      "    RequirementParseError\n",
      "   InvalidVersion\n",
      "  AssertionError\n",
      "  ArithmeticError\n",
      "   FloatingPointError\n",
      "   OverflowError\n",
      "   ZeroDivisionError\n",
      "    DivisionByZero\n",
      "    DivisionUndefined\n",
      "   DecimalException\n",
      "    Clamped\n",
      "    Rounded\n",
      "     Underflow\n",
      "     Overflow\n",
      "    Inexact\n",
      "     Underflow\n",
      "     Overflow\n",
      "    Subnormal\n",
      "     Underflow\n",
      "    DivisionByZero\n",
      "    FloatOperation\n",
      "    InvalidOperation\n",
      "     ConversionSyntax\n",
      "     DivisionImpossible\n",
      "     DivisionUndefined\n",
      "     InvalidContext\n",
      "  SystemError\n",
      "   CodecRegistryError\n",
      "  ReferenceError\n",
      "  MemoryError\n",
      "  BufferError\n",
      "  Warning\n",
      "   UserWarning\n",
      "    GetPassWarning\n",
      "    FormatterWarning\n",
      "   EncodingWarning\n",
      "   DeprecationWarning\n",
      "    ProvisionalWarning\n",
      "   PendingDeprecationWarning\n",
      "   SyntaxWarning\n",
      "   RuntimeWarning\n",
      "    ProactorSelectorThreadWarning\n",
      "    UnknownTimezoneWarning\n",
      "    PEP440Warning\n",
      "   FutureWarning\n",
      "    ProvisionalCompleterWarning\n",
      "   ImportWarning\n",
      "   UnicodeWarning\n",
      "   BytesWarning\n",
      "   ResourceWarning\n",
      "   DeprecatedTzFormatWarning\n",
      "   PkgResourcesDeprecationWarning\n",
      "  _OptionError\n",
      "  _Error\n",
      "  error\n",
      "  Verbose\n",
      "  Error\n",
      "  SubprocessError\n",
      "   CalledProcessError\n",
      "   TimeoutExpired\n",
      "  TokenError\n",
      "  StopTokenizing\n",
      "  ClassFoundException\n",
      "  EndOfBlock\n",
      "  TraitError\n",
      "  Error\n",
      "  Error\n",
      "   CancelledError\n",
      "   TimeoutError\n",
      "   InvalidStateError\n",
      "  _GiveupOnSendfile\n",
      "  error\n",
      "  Incomplete\n",
      "  TimeoutError\n",
      "  InvalidStateError\n",
      "  LimitOverrunError\n",
      "  QueueEmpty\n",
      "  QueueFull\n",
      "  Empty\n",
      "  Full\n",
      "  ArgumentError\n",
      "  ZMQBaseError\n",
      "   ZMQError\n",
      "    ContextTerminated\n",
      "    Again\n",
      "    InterruptedSystemCall\n",
      "   ZMQBindError\n",
      "   NotDone\n",
      "  PickleError\n",
      "   PicklingError\n",
      "   UnpicklingError\n",
      "  _Stop\n",
      "  ArgumentError\n",
      "  ArgumentTypeError\n",
      "  ConfigError\n",
      "   ConfigLoaderError\n",
      "    ArgumentError\n",
      "   ConfigFileNotFound\n",
      "  ConfigurableError\n",
      "   MultipleInstanceError\n",
      "  ApplicationError\n",
      "  error\n",
      "  TimeoutError\n",
      "  error\n",
      "  ReturnValueIgnoredError\n",
      "  KeyReuseError\n",
      "  UnknownKeyError\n",
      "  LeakedCallbackError\n",
      "  BadYieldError\n",
      "  ReturnValueIgnoredError\n",
      "  Return\n",
      "  InvalidPortNumber\n",
      "  error\n",
      "  LZMAError\n",
      "  RegistryError\n",
      "  _GiveupOnFastCopy\n",
      "  Error\n",
      "   NoSectionError\n",
      "   DuplicateSectionError\n",
      "   DuplicateOptionError\n",
      "   NoOptionError\n",
      "   InterpolationError\n",
      "    InterpolationMissingOptionError\n",
      "    InterpolationSyntaxError\n",
      "    InterpolationDepthError\n",
      "   ParsingError\n",
      "    MissingSectionHeaderError\n",
      "  NoIPAddresses\n",
      "  BadZipFile\n",
      "  LargeZipFile\n",
      "  BadEntryPoint\n",
      "  NoSuchEntryPoint\n",
      "  DuplicateKernelError\n",
      "  ErrorDuringImport\n",
      "  NotOneValueFound\n",
      "  CannotEval\n",
      "  OptionError\n",
      "  BdbQuit\n",
      "  Restart\n",
      "  ExceptionPexpect\n",
      "   EOF\n",
      "   TIMEOUT\n",
      "  PtyProcessError\n",
      "  FindCmdError\n",
      "  HomeDirError\n",
      "  ProfileDirError\n",
      "  IPythonCoreError\n",
      "   TryNext\n",
      "   UsageError\n",
      "   StdinNotImplementedError\n",
      "  InputRejected\n",
      "  GetoptError\n",
      "  ErrorToken\n",
      "  PrefilterError\n",
      "  AliasError\n",
      "   InvalidAliasError\n",
      "  Error\n",
      "   InterfaceError\n",
      "   DatabaseError\n",
      "    InternalError\n",
      "    OperationalError\n",
      "    ProgrammingError\n",
      "    IntegrityError\n",
      "    DataError\n",
      "    NotSupportedError\n",
      "  Warning\n",
      "  SpaceInInput\n",
      "  DOMException\n",
      "   IndexSizeErr\n",
      "   DomstringSizeErr\n",
      "   HierarchyRequestErr\n",
      "   WrongDocumentErr\n",
      "   InvalidCharacterErr\n",
      "   NoDataAllowedErr\n",
      "   NoModificationAllowedErr\n",
      "   NotFoundErr\n",
      "   NotSupportedErr\n",
      "   InuseAttributeErr\n",
      "   InvalidStateErr\n",
      "   SyntaxErr\n",
      "   InvalidModificationErr\n",
      "   NamespaceErr\n",
      "   InvalidAccessErr\n",
      "   ValidationErr\n",
      "  ValidationError\n",
      "  EditReadOnlyBuffer\n",
      "  _Retry\n",
      "  InvalidLayoutError\n",
      "  HeightIsUnknownError\n",
      "  ParserSyntaxError\n",
      "  InternalParseError\n",
      "  _PositionUpdatingFinished\n",
      "  SimpleGetItemNotFound\n",
      "  UncaughtAttributeError\n",
      "  HasNoContext\n",
      "  ParamIssue\n",
      "  _JediError\n",
      "   InternalError\n",
      "   WrongVersion\n",
      "   RefactoringError\n",
      "  OnErrorLeaf\n",
      "  InvalidPythonEnvironment\n",
      "  MessageError\n",
      "   MessageParseError\n",
      "    HeaderParseError\n",
      "    BoundaryError\n",
      "   MultipartConversionError\n",
      "   CharsetError\n",
      "  Error\n",
      "  HTTPException\n",
      "   NotConnected\n",
      "   InvalidURL\n",
      "   UnknownProtocol\n",
      "   UnknownTransferEncoding\n",
      "   UnimplementedFileMode\n",
      "   IncompleteRead\n",
      "   ImproperConnectionState\n",
      "    CannotSendRequest\n",
      "    CannotSendHeader\n",
      "    ResponseNotReady\n",
      "   BadStatusLine\n",
      "    RemoteDisconnected\n",
      "   LineTooLong\n",
      "  InteractivelyDefined\n",
      "  KillEmbedded\n",
      "  Error\n",
      "   NoSuchProcess\n",
      "    ZombieProcess\n",
      "   AccessDenied\n",
      "   TimeoutExpired\n",
      "  _Ipv6UnsupportedError\n",
      "  QueueEmpty\n",
      "  QueueFull\n",
      "  DebuggerInitializationError\n",
      "  ExpatError\n",
      "  Error\n",
      "   ProtocolError\n",
      "   ResponseError\n",
      "   Fault\n",
      "  ParseBaseException\n",
      "   ParseException\n",
      "   ParseFatalException\n",
      "    ParseSyntaxException\n",
      "  RecursiveGrammarException\n",
      "  ResolutionError\n",
      "   VersionConflict\n",
      "    ContextualVersionConflict\n",
      "   DistributionNotFound\n",
      "   UnknownExtra\n",
      "  _Error\n",
      "  UnableToResolveVariableException\n",
      "  InvalidTypeInArgsException\n",
      " GeneratorExit\n",
      " SystemExit\n",
      " KeyboardInterrupt\n",
      " CancelledError\n",
      " AbortThread\n"
     ]
    }
   ],
   "source": [
    "print_exception_hierarchy(BaseException)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "442bc258-0695-4a43-9c6b-58868a79abeb",
   "metadata": {},
   "source": [
    "__Note:__ This program uses recursion to traverse the exception hierarchy starting from the BaseException class. It prints each exception class's name with an appropriate level of indentation."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "070c8216-b404-4c04-a22f-f8cdde99a6ee",
   "metadata": {},
   "source": [
    "### Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "#### Answer:"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "20bdedeb-5dec-4149-b4ef-713a79a7a927",
   "metadata": {},
   "source": [
    "The ArithmeticError class in Python defines errors that occur during arithmetic operations. Two examples of errors defined in the ArithmeticError class are ZeroDivisionError and OverflowError.\n",
    "\n",
    "#### 1. ZeroDivisionError: \n",
    "- This error occurs when you try to divide a number by zero, which is mathematically undefined. \n",
    "\n",
    "#### Example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9d4a4232-88c9-4136-b445-68f13e90f674",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError as e:\n",
    "    print(\"Error:\", e)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1615b478-f9cb-4a49-b989-edbf75303f28",
   "metadata": {},
   "source": [
    "#### 2. OverflowError: \n",
    "- This error occurs when the result of an arithmetic operation exceeds the maximum representable value for a numeric type. \n",
    "\n",
    "#### Example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "238a47eb-69c0-46a7-aa4c-cfea43cbf3ab",
   "metadata": {},
   "outputs": [],
   "source": [
    "import math"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "c6977e39-2688-435c-a8b5-845fb99c520d",
   "metadata": {},
   "outputs": [
    {
     "ename": "OverflowError",
     "evalue": "math range error",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOverflowError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[14], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m x \u001b[38;5;241m=\u001b[39m \u001b[43mmath\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexp\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m1000\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28mprint\u001b[39m(x)\n",
      "\u001b[0;31mOverflowError\u001b[0m: math range error"
     ]
    }
   ],
   "source": [
    "x = math.exp(1000)\n",
    "print(x)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "788f3f31-561a-44d5-8050-b6c51cd224e7",
   "metadata": {},
   "source": [
    "### Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "#### Answer:"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7749b610-1143-4e55-a2c2-db0f803b9d39",
   "metadata": {},
   "source": [
    "The LookupError class is used as the base class for exceptions that are raised when a lookup or indexing operation fails. It provides a common base class for exceptions like KeyError and IndexError.\n",
    "\n",
    "#### 1. KeyError: \n",
    "- This error is raised when you try to access a dictionary using a key that does not exist. \n",
    "\n",
    "#### Example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "9ea1cd1a-f9fd-4b8f-acde-ef58d16c3fc6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: 'height'\n"
     ]
    }
   ],
   "source": [
    "my_dict = {\"name\": \"John\", \"age\": 30}\n",
    "\n",
    "try:\n",
    "    value = my_dict[\"height\"]\n",
    "except KeyError as e:\n",
    "    print(\"Error:\", e)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aea31223-22f1-43b9-9a3e-4eb3e7d46d77",
   "metadata": {},
   "source": [
    "#### 2. IndexError: \n",
    "This error is raised when you try to access a list, tuple, or string using an invalid index (an index that is out of range). \n",
    "\n",
    "#### Example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "f375a4d5-965d-4503-8718-913594e424b2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: list index out of range\n"
     ]
    }
   ],
   "source": [
    "my_list = [1, 2, 3]\n",
    "\n",
    "try:\n",
    "    value = my_list[3]\n",
    "except IndexError as e:\n",
    "    print(\"Error:\", e)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4a9dce4a-18b2-4354-8112-59cda6f826d4",
   "metadata": {},
   "source": [
    "### Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "#### Answer:"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ddd823f0-a6c8-42a2-b0ab-014f96194a0c",
   "metadata": {},
   "source": [
    "- ImportError is a built-in exception in Python that is raised when an import statement fails to find or load a module. It indicates a problem with importing a module or one of its dependencies. This error can occur due to various reasons, such as a misspelled module name, an incorrect file path, or a missing dependency.\n",
    "\n",
    "\n",
    "- ModuleNotFoundError is a subclass of ImportError that specifically indicates that the requested module could not be found. It was introduced in Python 3.6 to provide a more specific error message for import failures.\n",
    "\n",
    "\n",
    "- For example, if you try to import a module that does not exist, you will encounter a ModuleNotFoundError:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "fb4509e0-b4ce-4094-b25b-da4654ad3388",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError as e:\n",
    "    print(\"Error:\", e)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2e3a7de9-3fee-4794-8274-88abdbe8bc14",
   "metadata": {},
   "source": [
    "### Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "#### Answer:"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a7e3f7aa-6966-4beb-9e1e-2b2a3fab33ef",
   "metadata": {},
   "source": [
    "- __Be specific with exception handling:__ \n",
    "\n",
    "Catch specific exceptions instead of using a broad except clause. This allows you to handle different exceptions differently and avoids unintentionally catching and suppressing unrelated exceptions.\n",
    "\n",
    "- __Use multiple except blocks:__ \n",
    "\n",
    "When handling different exceptions, use separate except blocks for each exception type. This improves code readability and allows for specific exception handling logic.\n",
    "\n",
    "- __Use finally for cleanup:__ \n",
    "\n",
    "If you have code that should always run, regardless of whether an exception occurred, place it in a finally block. This ensures proper cleanup of resources.\n",
    "\n",
    "- __Avoid bare except clauses:__ \n",
    "Avoid using a bare except clause without specifying the exception type. It can hide errors and make debugging difficult. If you need to catch multiple exceptions, list them explicitly or catch the base Exception class.\n",
    "\n",
    "- __Reraise exceptions when necessary:__ \n",
    "If you catch an exception but cannot handle it appropriately, it's often better to reraise the exception using raise without any arguments. This preserves the exception's traceback and allows higher-level exception handlers to handle it.\n",
    "\n",
    "- __Provide informative error messages:__ \n",
    "When raising or catching exceptions, include descriptive error messages to help with debugging. The error message should provide enough information to understand the cause of the exception.\n",
    "\n",
    "- __Use context managers (with statement):__ \n",
    "Utilize context managers to handle resources that need to be properly managed, such as file operations or database connections. Context managers ensure that resources are released correctly, even if exceptions occur.\n",
    "\n",
    "- __Log exceptions:__ \n",
    "Consider logging exceptions using a logging framework instead of just printing error messages. Logging provides a centralized way to record and analyze exceptions, making it easier to troubleshoot issues."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c6ae2f45-6b3f-4cac-a830-69394df190d0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
